import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#7A5AF8",
          dark: "#4A1FB8",
          darker: "#0C0C0C",
        },
        shade: {
          DEFAULT: "#140832",
          light: "#28116",
          dark: "#361786",
          darker: "#4a1fb8",
          darkest: "#5825da",
        },
        tint: {
          lightest: "#f2eefc",
          lighter: "#cbbbf4",
          light: "#a489eb",
          DEFAULT: "#7e56e3",
          dark: "#6435dd",
        },
        gray: {
          DEFAULT: "#d6d6d6",
          lightest: "#ffffff",
          lighter: "#f5f5f5",
          light: "#ebebeb",
          normal: "#e0e0e0",
          dark: "#b8b8b8",
          darker: "#adadad",
          darkest: "#a3a3a3",
          200: "#cccccc",
          300: "#c2c2c2",
          400: "#999999",
          500: "#8f8f8f",
          600: "#858585",
        },
        black: {
          DEFAULT: "#667085",
          dark: "#475467",
          darker: "#344054",
          darkest: "#1D2939",
          extraDark: "#101828",
          light: "#FCFCFD",
          lighter: "#F2F4F7",
          lightest: "#F9FAFB",
          extraLight: "#E4E7EC",
          muted: "#D0D5DD",
          dim: "#98A2B3",
        },
        state: {
          error: "#B81F40",
          success: "#8DB81F",
          info: "#004AB9",
          warning: "#FFC000",
        },
      },
      fontSize: {
        'display-1': '74px',
        'display-2': '64px',
        'display-3': '56px',
        'h1': '40px',
        'h2': '32px',
        'h3': '24px',
        'h4': '20px',
        'h5': '18px',
        'h6': '16px',
        'subtitle-1': '20px',
        'subtitle-2': '18px',
        'subtitle-3': '16px',
        'body-1': '18px',
        'body-2': '16px',
        'body-3': '14px',
        'button-1': '16px',
        'button-2': '14px',
        'caption-1': '14px',
        'caption-2': '12px',
        'overline-1': '14px',
        'overline-2': '12px',
      },
      fontFamily: {
        'times-new-roman': ['Times New Roman', 'serif'],
        'plus-jakarta-display': ['Plus Jakarta Display', 'sans-serif'],
      },
      
      container: {
        center: true,
        padding: {
          DEFAULT: '1rem',
          sm: '2rem',
          lg: '4rem',
          xl: '5rem',
          '2xl': '6rem',
        },
      },
    },
  },
  plugins: [],
} satisfies Config;