import type { Metadata } from "next";
import "./globals.css";
import { plusJakartaSans } from "@/utils/fonts";
import QueryProvider from "@/components/QueryProvider";
import { ToastContainer } from "react-toastify";
import { AlertProvider } from "@/contexts/alertContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${plusJakartaSans.className}`}>
        <AlertProvider>
          <QueryProvider>{children}</QueryProvider>
          <ToastContainer position="bottom-right" />
        </AlertProvider>
      </body>
    </html>
  );
}
