import type { Metadata } from "next";
import "./globals.css";
import { plusJakartaSans } from "./utility/fonts";
import Header from "./components/ui/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased ${plusJakartaSans.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
